version: '3.1'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mydb
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    labels:
      - 'name=redis'
      - 'mode=standalone'
    ports:
      - 6379:6379
    volumes:
      - ./data/redis/data:/data
      - ./data/redis/conf:/usr/local/etc/redis/redis.conf
    command:
      - redis-server
