// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kyh0703/stock-server/ent/posts"
	"github.com/kyh0703/stock-server/ent/users"
)

// PostsCreate is the builder for creating a Posts entity.
type PostsCreate struct {
	config
	mutation *PostsMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (pc *PostsCreate) SetTitle(s string) *PostsCreate {
	pc.mutation.SetTitle(s)
	return pc
}

// SetBody sets the "body" field.
func (pc *PostsCreate) SetBody(s string) *PostsCreate {
	pc.mutation.SetBody(s)
	return pc
}

// SetTags sets the "tags" field.
func (pc *PostsCreate) SetTags(s []string) *PostsCreate {
	pc.mutation.SetTags(s)
	return pc
}

// SetPublishAt sets the "publishAt" field.
func (pc *PostsCreate) SetPublishAt(t time.Time) *PostsCreate {
	pc.mutation.SetPublishAt(t)
	return pc
}

// SetNillablePublishAt sets the "publishAt" field if the given value is not nil.
func (pc *PostsCreate) SetNillablePublishAt(t *time.Time) *PostsCreate {
	if t != nil {
		pc.SetPublishAt(*t)
	}
	return pc
}

// SetUserID sets the "user" edge to the Users entity by ID.
func (pc *PostsCreate) SetUserID(id int) *PostsCreate {
	pc.mutation.SetUserID(id)
	return pc
}

// SetNillableUserID sets the "user" edge to the Users entity by ID if the given value is not nil.
func (pc *PostsCreate) SetNillableUserID(id *int) *PostsCreate {
	if id != nil {
		pc = pc.SetUserID(*id)
	}
	return pc
}

// SetUser sets the "user" edge to the Users entity.
func (pc *PostsCreate) SetUser(u *Users) *PostsCreate {
	return pc.SetUserID(u.ID)
}

// Mutation returns the PostsMutation object of the builder.
func (pc *PostsCreate) Mutation() *PostsMutation {
	return pc.mutation
}

// Save creates the Posts in the database.
func (pc *PostsCreate) Save(ctx context.Context) (*Posts, error) {
	var (
		err  error
		node *Posts
	)
	pc.defaults()
	if len(pc.hooks) == 0 {
		if err = pc.check(); err != nil {
			return nil, err
		}
		node, err = pc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PostsMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = pc.check(); err != nil {
				return nil, err
			}
			pc.mutation = mutation
			if node, err = pc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(pc.hooks) - 1; i >= 0; i-- {
			if pc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, pc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Posts)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from PostsMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PostsCreate) SaveX(ctx context.Context) *Posts {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *PostsCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *PostsCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pc *PostsCreate) defaults() {
	if _, ok := pc.mutation.PublishAt(); !ok {
		v := posts.DefaultPublishAt()
		pc.mutation.SetPublishAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *PostsCreate) check() error {
	if _, ok := pc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Posts.title"`)}
	}
	if _, ok := pc.mutation.Body(); !ok {
		return &ValidationError{Name: "body", err: errors.New(`ent: missing required field "Posts.body"`)}
	}
	if _, ok := pc.mutation.Tags(); !ok {
		return &ValidationError{Name: "tags", err: errors.New(`ent: missing required field "Posts.tags"`)}
	}
	if _, ok := pc.mutation.PublishAt(); !ok {
		return &ValidationError{Name: "publishAt", err: errors.New(`ent: missing required field "Posts.publishAt"`)}
	}
	return nil
}

func (pc *PostsCreate) sqlSave(ctx context.Context) (*Posts, error) {
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (pc *PostsCreate) createSpec() (*Posts, *sqlgraph.CreateSpec) {
	var (
		_node = &Posts{config: pc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: posts.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: posts.FieldID,
			},
		}
	)
	if value, ok := pc.mutation.Title(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: posts.FieldTitle,
		})
		_node.Title = value
	}
	if value, ok := pc.mutation.Body(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: posts.FieldBody,
		})
		_node.Body = value
	}
	if value, ok := pc.mutation.Tags(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: posts.FieldTags,
		})
		_node.Tags = value
	}
	if value, ok := pc.mutation.PublishAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: posts.FieldPublishAt,
		})
		_node.PublishAt = value
	}
	if nodes := pc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   posts.UserTable,
			Columns: []string{posts.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: users.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.users_posts = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PostsCreateBulk is the builder for creating many Posts entities in bulk.
type PostsCreateBulk struct {
	config
	builders []*PostsCreate
}

// Save creates the Posts entities in the database.
func (pcb *PostsCreateBulk) Save(ctx context.Context) ([]*Posts, error) {
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Posts, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PostsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *PostsCreateBulk) SaveX(ctx context.Context) []*Posts {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *PostsCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *PostsCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}
