// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Posts is the predicate function for posts builders.
type Posts func(*sql.Selector)

// Users is the predicate function for users builders.
type Users func(*sql.Selector)
